NRI-HTML初回提出
RYU1030/Ryunosuke-Fukuda pull request #1
Opened 2020-03-30 06:46 UTC by RYU1030

2020-03-31 08:10 UTC, nozomi71 commented on index.html
> +    <div class="main-container">
このブロックいらないですね

2020-03-31 08:10 UTC, nozomi71 commented on index.html
> +      <h3>企業情報</h3>
2がないのに突然3？

2020-03-31 08:10 UTC, nozomi71 commented on index.html
> +        <div class="an-info-section">
このブロックいらないです

2020-03-31 08:10 UTC, nozomi71 commented on index.html
> +  <div class="follow-us">
このブロックもいらないです

2020-03-31 08:10 UTC, nozomi71 commented on index.html
> +  <p class="copy-right">Copyright(c) Nomura Research Institute, Ltd. All rights reserved.</p>
`address`タグの方がいいですね

2020-03-31 09:15 UTC, RYU1030 commented on index.html
> +    <div class="main-container">
divタグを削除し、sectionタグにclass名 main-containerを追加しました。

2020-03-31 09:17 UTC, RYU1030 commented on index.html
> +      <h3>企業情報</h3>
section .main-container 内の見出しを h2 にしているので、こちらの見出しはh3 にしました。

2020-03-31 09:23 UTC, RYU1030 commented on index.html
> +        <div class="an-info-section">
section の内側に設けていた div ブロックを削除し、section に class名 info-container を追加しました。

2020-03-31 09:26 UTC, RYU1030 commented on index.html
> +  <div class="follow-us">
div ブロックを削除し、ulタグにクラス名 follow-us を追加しました。

2020-03-31 09:26 UTC, RYU1030 commented on index.html
> +  <p class="copy-right">Copyright(c) Nomura Research Institute, Ltd. All rights reserved.</p>
address タグに変更しました。

2020-03-31 12:47 UTC, nozomi71 commented on index.html
> +  <section>
ここは`section`いらないですね

2020-03-31 12:47 UTC, nozomi71 commented on index.html
> +      <p>NRIの強み</p>
これ見出しですね

2020-03-31 12:47 UTC, nozomi71 commented on index.html
> +      <h3>企業情報</h3>
ここの`section`と同列なのでそれならh2ですね

2020-04-01 03:44 UTC, RYU1030 commented on index.html
> +  <section>
sectionタグを削除しました。

2020-04-01 03:48 UTC, RYU1030 commented on index.html
> +      <p>NRIの強み</p>
h タグで囲みました。

2020-04-01 03:48 UTC, RYU1030 commented on index.html
> +      <h3>企業情報</h3>
h2 に置換しました。

2020-04-01 06:08 UTC, piasoratech approved these changes

2020-04-01 06:10 UTC, piasoratech requested changes
すいませんOKじゃなかったです！
HTMLの構文チェックかけてエラーつぶして再提出お願いします！

2020-04-02 03:45 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-02 03:45 UTC, piasoratech commented on index.html
> +    <h1>NRIのデジタルビジネス戦略</h1>
`section`タグないしはそれに準拠するタグがないです

2020-04-02 03:45 UTC, piasoratech commented on index.html
> +      <h2>NRIの強み</h2>
ここも同様です

2020-04-02 03:45 UTC, piasoratech commented on index.html
> +  <ul class="footer-bottom">
`footer`タグ使うならここからですね～

2020-04-02 03:49 UTC, RYU1030 commented on index.html
> +    <h1>NRIのデジタルビジネス戦略</h1>
div タグ class="page-title" を追加しました！

2020-04-02 04:05 UTC, RYU1030 commented on index.html
> +  <ul class="footer-bottom">
footer タグの開始位置を変更しました。

2020-04-02 05:15 UTC, RYU1030 commented on index.html
> +      <h2>NRIの強み</h2>
section タグで hタグとulタグを囲いました。

2020-04-02 05:19 UTC, RYU1030 commented
マークアップ構造を一部変更。divタグを追加しています。
SNSアイコンをfont-awesomeでの実装に変更しました。
指摘事項を修正。

2020-04-06 06:04 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
HTMLの確認のみ行っています。

2020-04-06 06:46 UTC, piasoratech requested changes
コメント反映されていなかったようなので再度コメントしました。
確認をお願いします！

2020-04-06 06:46 UTC, piasoratech commented on index.html
> +</div>
ここがfooterではなくなったのでidやclass名を変更しましょう。
また、マジックナンバーを使用するのはやめましょう

2020-04-06 07:48 UTC, RYU1030 commented on index.html
> +</div>
Class名を変更しました。マジックナンバーを削除しました。

2020-04-06 07:49 UTC, RYU1030 commented
指摘事項を修正し、不要と思われるタグを一部削除しました。

2020-04-07 03:16 UTC, piasoratech approved these changes
良いかと！
次に進みましょう！

2020-04-08 06:01 UTC, RYU1030 commented
CSSファイル初回提出。

2020-04-09 07:40 UTC, piasoratech requested changes
企業情報の部分とFollowUsより下の部分本家はリンクになっているので修正して下さい。
あと全体的に`>`の見た目が本家と比べると大きいかなという気がするのでもう少し小さくしましょう。

2020-04-10 02:47 UTC, RYU1030 commented
指摘事項に対応いたしました。
> の見た目を実物と同じにするため、画像ファイルをダウンドードし、ブランチにもアップロードしています。
リンクホバー時の挙動も、本家のサイトと同じになるよう、コードを実装しました。

2020-04-10 02:58 UTC, RYU1030 commented
指摘事項に対応いたしました。
">" の見た目を実物と同じにするため、画像ファイルをダウンドードし、ブランチにもアップロードしています。
リンクホバー時の挙動も、本家のサイトと同じになるよう、コードを実装しました。

2020-04-10 04:18 UTC, piasoratech requested changes
![image](https://user-images.githubusercontent.com/57445698/78961849-bb0a9880-7b2d-11ea-8243-d1f58ccf6dea.png)
ここの「NRIの強み」のフォント装飾もう少し本家に寄せましょうか

2020-04-10 04:18 UTC, piasoratech commented on index.html
> +        <li><a href="#">株主•投資家情報(IR)</a></li>
すいません。マークアップで気になっていたんですがここの中黒丸って何を使ってますか？

2020-04-10 05:01 UTC, RYU1030 commented on index.html
> +        <li><a href="#">株主•投資家情報(IR)</a></li>
”・”の半角が”•”です..。本家に寄せたつもりですが、全角の方が良いでしょうか。

2020-04-10 06:03 UTC, RYU1030 commented
「NRIの強み」の装飾を近づけるため、CSSを記述しました。

2020-04-10 06:41 UTC, piasoratech commented on index.html
> +        <li><a href="#">株主•投資家情報(IR)</a></li>
普通の"・”でいいかなと思いましたが…
まあ今の状態で大丈夫です。

2020-04-10 06:41 UTC, piasoratech requested changes
![image](https://user-images.githubusercontent.com/57445698/78969364-bf40b100-7b41-11ea-983e-49a305494140.png)
よく見たらここも本家と違ってますね…
何度もすいませんが修正をお願いします！

2020-04-10 06:54 UTC, RYU1030 commented
左右のpaddingを変更して、見た目を再現しました。

2020-04-10 07:02 UTC, piasoratech requested changes
![image](https://user-images.githubusercontent.com/57445698/78970589-9bcb3580-7b44-11ea-9467-99c8b31a0a79.png)

今度は箱のサイズが違ってますね

2020-04-10 07:16 UTC, RYU1030 commented
ご指摘の点を修正致しました。

2020-04-10 07:21 UTC, piasoratech approved these changes
良いと思います！

2020-04-11 08:31 UTC, merged