Html kaguya
RYU1030/Ryunosuke-Fukuda pull request #2
Opened 2020-04-01 06:32 UTC by RYU1030

2020-04-06 04:05 UTC, RYU1030 commented
cca4455 が今回提出分です。

2020-04-06 08:07 UTC, RYU1030 commented
HTMLファイルの初回提出となります。

2020-04-07 04:10 UTC, fjtawork commented
良いかと！
LGTMです

2020-04-13 06:42 UTC, RYU1030 commented
CSSファイル初回提出です。

2020-04-13 07:20 UTC, piasoratech requested changes
・ヘッダー部分は選択されていないページについて見本では文字色が変わっているので確認をお願いします。
![image](https://user-images.githubusercontent.com/57445698/79100980-9a974400-7da2-11ea-8a94-de667909577b.png)


・「暮らしを提案する」の部分が全体的にNEWS部分と比べると左に寄っているので確認をお願いします。
![image](https://user-images.githubusercontent.com/57445698/79100930-83f0ed00-7da2-11ea-961f-d00b4c6cadfd.png)

2020-04-13 08:11 UTC, RYU1030 commented
修正点
1. ヘッダー部分は選択されていないページの文字色を見本と同じになるようにコードを実装しました。
2. 「暮らしを提案する」の部分が、画面中央に表示されるようにコードを修正しました。

2020-04-13 08:12 UTC, RYU1030 commented
> 修正点
> 
> 1. ヘッダー部分は選択されていないページの文字色を見本と同じになるようにコードを実装しました。
> 2. 「暮らしを提案する」の部分が、画面中央に表示されるようにコードを修正しました。

2020-04-13 08:19 UTC, RYU1030 commented
修正点
・選択されていないページのリンク文字色が、見本と同じになるようにコードを実装しました。
・「暮らしを提案する」の部分が、画面中央に表示されるようにコードを修正しました。

2020-04-13 08:37 UTC, piasoratech requested changes
・この部分は見本と比べるとわかると思うのですが、「暮らしを提案する。」のほうがNEWSの一番左の画像よりも少し外にいます。今提出いただいているものだと逆転してしまっているので、確認をお願いします。
![image](https://user-images.githubusercontent.com/57445698/79106443-7b51e400-7dad-11ea-9d54-e5f4ee050bd9.png)

2020-04-13 09:37 UTC, RYU1030 commented
message-wrapper と news-wrapper にmax-widthを指定、左右のmarginをautoに指定し、画面中央に配置。

2020-04-14 02:52 UTC, piasoratech approved these changes
良いかと！
次に進みましょう！

2020-04-15 03:19 UTC, RYU1030 commented
「家具屋Home」レスポンシブデザインの初回提出 43fe62b です。
- ハンバーガーメニュー未実装。
- view more のリンクは、詳細ページのブランチと本ブランチをマージ後に機能します。

2020-04-15 05:04 UTC, choimake commented
375pxの画面を確認したところ、
HTMLが375pxより大きいコンテンツなっており、はみ出ているので修正お願いします。
(HTML CSSのロゴが中央からズレているところからもわかると思います。)

<img width="378" alt="スクリーンショット 2020-04-15 13 55 34" src="https://user-images.githubusercontent.com/52233450/79300464-c12fb900-7f21-11ea-92d9-8ce706bb7a61.png">

2020-04-15 05:20 UTC, choimake commented
申し訳ありません。
上記のズレはこちらの誤操作によるもので、通常のページ読み込みの際には発生しないものと思われるので、修正の必要はありません。
LGTMです。

2020-04-15 06:01 UTC, choimake commented on kaguya-kadai/home/index.html
> +    <a class="details" href="../news/index.html">view more<i class="fa fa-angle-right"></i><a>
<a>が開いたままになっているので、こちらのタグを閉じタグに修正お願いします。

2020-04-15 06:20 UTC, RYU1030 commented on kaguya-kadai/home/index.html
> +    <a class="details" href="../news/index.html">view more<i class="fa fa-angle-right"></i><a>
ご指摘ありがとうございます。
修正致しました！

2020-04-15 06:20 UTC, RYU1030 commented
マークアップのエラーを修正致しました。

2020-04-15 06:42 UTC, choimake commented
対応ありがとうございます。
LGTMです！

2020-04-16 00:57 UTC, merged