「家具屋課題 News, Recruit, Contactページ」
RYU1030/Ryunosuke-Fukuda pull request #4
Opened 2020-04-06 02:37 UTC by RYU1030

2020-04-06 07:43 UTC, RYU1030 commented
各ページごとのマークアップファイル初回提出となります。

2020-04-07 04:54 UTC, fjtawork commented
news/index.htmlを構文チェックをしたらエラー出てたので、
同じようにチェックしてもらって、修正しましょう！

html構文チェックのサイトはこちらです
https://validator.w3.org/#validate_by_input

2020-04-09 01:30 UTC, RYU1030 commented
チェッカーにて全てのファイルの構文にエラーがなきこと確認しました。

2020-04-09 09:38 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-09 09:38 UTC, piasoratech commented on kaguya-kadai/news/index.html
> +      <p>アームストロングのチェア入荷</p>
ここ文面違いますね

2020-04-09 09:38 UTC, piasoratech commented on kaguya-kadai/news/index.html
> +        <li>CONTACT</li>
ここはリンクにしておきましょう。
他のページも同様です

2020-04-09 09:38 UTC, piasoratech commented on kaguya-kadai/news/index.html
> +        <li>CONTACT</li>
ここはリンクにしておきましょう
他のページも同様です

2020-04-09 09:38 UTC, piasoratech commented on kaguya-kadai/news/index.html
> +    <address>@HTMLCSS.code</address>
これ課題側が間違ってたんですが、@ではなくてコピーライトのマークに変更してもらっていいですか？
またそれを踏まえてタグつけをお願いします！
(他のページも同様)

2020-04-09 09:38 UTC, piasoratech commented on kaguya-kadai/recruit/index.html
> +          <td>仕事内容<br>・海外から輸入している家具の販売 <br>・商品管理 <br>・オーダーメイド家具の発注</td>
リストにしましょう

2020-04-09 09:38 UTC, piasoratech commented on kaguya-kadai/recruit/index.html
> +          <td>時給<br>1,200円〜</td>
改行があるならコードも改行したほうが良いです。

2020-04-09 09:38 UTC, piasoratech commented on kaguya-kadai/recruit/index.html
> +          <td>仕事内容<br>・家具作成に必要な材料の発注<br>・商品管理 ・オーダーメイド家具の相談<br>・オーダーメイド家具のディレクション<br>・オーダーメイド家具の製作</td>
ここもリストに

2020-04-09 09:38 UTC, piasoratech commented on kaguya-kadai/contact/index.html
> +        <textarea name="query" id="query"></textarea>
`value`を使うとフォームに入力された状態になってしまうので、`placeholder`にしたほうが良いですね

`textarea`の`name`を`query`にした理由は何でしょう？

2020-04-09 09:38 UTC, piasoratech commented on kaguya-kadai/template/template.html
> +<!DOCTYPE html>
このファイルはどういった意図で作りました…？

2020-04-10 03:06 UTC, RYU1030 commented on kaguya-kadai/news/index.html
> +      <p>アームストロングのチェア入荷</p>
修正致しました！

2020-04-10 03:12 UTC, RYU1030 commented on kaguya-kadai/news/index.html
> +        <li>CONTACT</li>
修正致しました！

2020-04-10 03:12 UTC, RYU1030 commented on kaguya-kadai/news/index.html
> +        <li>CONTACT</li>
修正致しました！

2020-04-10 03:21 UTC, RYU1030 commented on kaguya-kadai/news/index.html
> +    <address>@HTMLCSS.code</address>
変更しました！

2020-04-10 03:25 UTC, RYU1030 commented on kaguya-kadai/recruit/index.html
> +          <td>仕事内容<br>・海外から輸入している家具の販売 <br>・商品管理 <br>・オーダーメイド家具の発注</td>
リストにしました！

2020-04-10 03:25 UTC, RYU1030 commented on kaguya-kadai/recruit/index.html
> +          <td>時給<br>1,200円〜</td>
改行しました！

2020-04-10 03:28 UTC, RYU1030 commented on kaguya-kadai/recruit/index.html
> +          <td>仕事内容<br>・家具作成に必要な材料の発注<br>・商品管理 ・オーダーメイド家具の相談<br>・オーダーメイド家具のディレクション<br>・オーダーメイド家具の製作</td>
リストにしました！

2020-04-10 03:39 UTC, RYU1030 commented on kaguya-kadai/contact/index.html
> +        <textarea name="query" id="query"></textarea>
placeholderに修正致しました！
nameに何かしら入力しないとコードチェッカーでエラーになるので、適当に命名しました..。

2020-04-10 03:42 UTC, RYU1030 commented on kaguya-kadai/template/template.html
> +<!DOCTYPE html>
templateフォルダは、news, recruit, contact ページに共通する画像やCSSのリファレンス先にするため、作成しました。それぞれのマークアップが終わったので、htmlファイルは不要になりましたが..。

2020-04-10 03:44 UTC, RYU1030 commented
指摘事項を修正し、頂いたコメントに返信を致しました。

2020-04-10 04:30 UTC, piasoratech commented on kaguya-kadai/contact/index.html
> +          <li><a href="#">HOME</a></li>
HOMEへはこのリンクではだめですね(他も同様)

2020-04-10 04:30 UTC, piasoratech commented on kaguya-kadai/contact/index.html
> +        <textarea name="query" id="query"></textarea>
適当な命名はやめましょう。命名するなら必ず意味が分かる名前を付けるのは絶対です！

2020-04-10 05:58 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
テンプレートに関しては理解しました！

2020-04-10 05:58 UTC, piasoratech commented on kaguya-kadai/recruit/index.html
> +            <br>週３〜5日
ここの３は見本が間違ってたので半角にしてください

2020-04-10 05:58 UTC, piasoratech commented on kaguya-kadai/recruit/index.html
> +            <br>10:00 - 19:00（1時間休憩
閉じかっこが消えてます。

2020-04-10 06:24 UTC, RYU1030 commented on kaguya-kadai/contact/index.html
> +        <textarea name="query" id="query"></textarea>
query は、英語で「問合せ」という意味なので、こちらの textarea の name としても適切かと思うのですが、いかがでしょうか..。🙇‍♂️

2020-04-10 06:25 UTC, RYU1030 commented on kaguya-kadai/contact/index.html
> +          <li><a href="#">HOME</a></li>
適切なリンクを指定しました！

2020-04-10 06:26 UTC, RYU1030 commented on kaguya-kadai/recruit/index.html
> +            <br>週３〜5日
半角にしました！

2020-04-10 06:26 UTC, RYU1030 commented on kaguya-kadai/recruit/index.html
> +            <br>10:00 - 19:00（1時間休憩
ご指摘ありがとうございます！

2020-04-10 06:28 UTC, RYU1030 commented
ご指摘の点、修正致しました！また、頂いたコメントに返信もさせて頂いております。

2020-04-10 06:54 UTC, piasoratech commented on kaguya-kadai/contact/index.html
> +        <textarea name="query" id="query"></textarea>
`query`というと個人的にはSQLなどで使うクエリをイメージするのでどうかな？と思いました。
`content`とか`detail`のほうがよさそうな気はします。
個人的な意見なので、このままでもOKです。
ただ、適当な命名(今回は結果として違いましたが)だけはやめるように覚えておいてください。

2020-04-10 06:59 UTC, piasoratech commented on kaguya-kadai/contact/index.html
> +          <li><a href="#">HOME</a></li>
リンク関係全部見直しました？

2020-04-10 07:00 UTC, piasoratech requested changes
ヘッダー側のリンク修正できてないのでそれ修正しましょう

2020-04-10 07:01 UTC, RYU1030 commented on kaguya-kadai/contact/index.html
> +        <textarea name="query" id="query"></textarea>
了解しました！ご指摘ありがとうございます！

2020-04-10 07:38 UTC, RYU1030 commented on kaguya-kadai/contact/index.html
> +          <li><a href="#">HOME</a></li>
爪が甘くすみません..。修正しました！

2020-04-10 07:40 UTC, RYU1030 commented
失礼致しました..。ヘッダー側のリンクを修正致しました。

2020-04-10 08:14 UTC, piasoratech approved these changes
OKです！次に進みましょう！

2020-04-14 01:53 UTC, RYU1030 commented
「家具屋News, Recruit, Contact」CSS初回提出となります。
詳細ページ3つへのリンクは機能しますが、Homeへのリンクは別ブランチ(html-kaguya)にファイルが保存されているため、現時点では機能せず、本ブランチとhtml-kaguyaのmasterへのマージ後に機能するようになります。

2020-04-14 03:47 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-14 03:47 UTC, piasoratech commented on kaguya-kadai/recruit/index.html
> +            <p>10:00 - 19:00（1時間休憩</p>
閉じかっこないですね。
指摘漏れすいません…。

2020-04-14 03:51 UTC, RYU1030 commented on kaguya-kadai/recruit/index.html
> +            <p>10:00 - 19:00（1時間休憩</p>
修正したはずなのに、反映されておりませんでした..。
修正しました！

2020-04-14 03:52 UTC, RYU1030 commented
ご指摘事項を修正しました。

2020-04-14 05:24 UTC, piasoratech approved these changes
良いかと！

2020-04-15 11:10 UTC, RYU1030 commented
News, Recruit, Contact ページ レスポンシブデザインの初回提出となります。

2020-04-16 02:39 UTC, piasoratech requested changes
・NEWSの画像内の文字が二行になってます。
![image](https://user-images.githubusercontent.com/57445698/79408540-92274f00-7fd6-11ea-9611-233773acb858.png)
・CONTACTの「お問い合わせ内容」だけフォントが違います。
![image](https://user-images.githubusercontent.com/57445698/79408611-b5ea9500-7fd6-11ea-9fa2-c8936d009e32.png)
・RECRUITは横スクロールが出ています。
![image](https://user-images.githubusercontent.com/57445698/79408702-eb8f7e00-7fd6-11ea-99dd-363839515244.png)

2020-04-16 02:39 UTC, piasoratech commented on kaguya-kadai/news/index.html
> +        <p>アームストロングのチェア入荷</p>
ここ見本と文面違いますね
指摘漏れててすいません。

2020-04-16 04:54 UTC, RYU1030 commented on kaguya-kadai/news/index.html
> +        <p>アームストロングのチェア入荷</p>
文面の違いが分からなかったのですが、見本からコピペし他ので大丈夫かと！

2020-04-16 05:04 UTC, RYU1030 commented
上記3点ですが、自分の画面ではレイアウトのずれ等の確認が出来ませんでした。
下記、3点の対応を致しましたので表示をご確認頂けますでしょうか。
1. News 画像内文字：letter-spacing のネガティブ値を上げてテキスト幅を縮小しました。
2. Contact 「お問い合わせ内容」：:placeholder に直接、 font-family: Noto Sans, sans-serif; を指定しました。
3. Recruit table はみ出し：.job-type 左右のpadding 値を下げ、セルの幅を縮小しました。

2020-04-16 06:34 UTC, piasoratech requested changes
再度確認したところ問題なかったのでOKとします。

2020-04-16 06:34 UTC, piasoratech commented on kaguya-kadai/recruit/style.css
> +@media screen and (min-width: 376px) {
これだとウインドウ幅が376px以上の場合に適用になってしまうのでここの書き方が違いますね

2020-04-16 08:10 UTC, piasoratech approved these changes

2020-04-17 05:32 UTC, merged